/**
 * Sidebar is fully autogenerated from the folder structure under `docs/`.
 *
 * To customize a category (label, emoji, position), add a `_category_.json`
 * inside that folder. To customize a doc's position within its category, add
 * `sidebar_position` to the doc's frontmatter.
 *
 * The legacy TinaCMS "Docs Sidebar" collection (`config/sidebar/index.json`)
 * is no longer wired in — kept on disk only as historical reference and can
 * be removed once the team is comfortable with the autogenerated flow.
 */
module.exports = {
  tutorialSidebar: [{ type: "autogenerated", dirName: "." }],
};
